ALTER TABLE negocio
  ADD COLUMN IF NOT EXISTS logo_data TEXT,
  ADD COLUMN IF NOT EXISTS fondo_tipo VARCHAR(20) NOT NULL DEFAULT 'claro',
  ADD COLUMN IF NOT EXISTS fondo_data TEXT,
  ADD COLUMN IF NOT EXISTS color_primario VARCHAR(7) NOT NULL DEFAULT '#d9ff43',
  ADD COLUMN IF NOT EXISTS color_secundario VARCHAR(7) NOT NULL DEFAULT '#171713';
